---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - echo "[default]" > ansible.cfg
  - echo "roles_path = ../" >> ansible.cfg
  - git clone https://github.com/vmware/ansible-role-vcenter.git

script:
  # Test syntax on playbook
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
